--
-- PostgreSQL database dump
--

\restrict PZc59U5p6ZkDKoiHLJsM2aRZ80eRQPFX7RFb7OaRsaLGNQl2AnqfbnEyghBpPpA

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: luckydna
--

CREATE TABLE public.app_user (
                                 id bigint NOT NULL,
                                 created_at timestamp(6) with time zone NOT NULL,
                                 email character varying(255) NOT NULL,
                                 full_name character varying(255) NOT NULL,
                                 password_hash character varying(255) NOT NULL,
                                 role character varying(20) DEFAULT 'USER'::character varying
);


ALTER TABLE public.app_user OWNER TO luckydna;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: luckydna
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: play_result; Type: TABLE; Schema: public; Owner: luckydna
--

CREATE TABLE public.play_result (
                                    id bigint NOT NULL,
                                    checked_at timestamp(6) with time zone,
                                    power_ball_match boolean,
                                    prize_amount numeric(38,2),
                                    prize_tier character varying(255),
                                    white_ball_matches integer,
                                    drawing_id bigint NOT NULL,
                                    saved_play_id bigint NOT NULL,
                                    user_id bigint NOT NULL
);


ALTER TABLE public.play_result OWNER TO luckydna;

--
-- Name: play_result_id_seq; Type: SEQUENCE; Schema: public; Owner: luckydna
--

ALTER TABLE public.play_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.play_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: powerball_drawing; Type: TABLE; Schema: public; Owner: luckydna
--

CREATE TABLE public.powerball_drawing (
                                          id bigint NOT NULL,
                                          drawing_date date,
                                          power_ball integer,
                                          white_ball1 integer,
                                          white_ball2 integer,
                                          white_ball3 integer,
                                          white_ball4 integer,
                                          white_ball5 integer
);


ALTER TABLE public.powerball_drawing OWNER TO luckydna;

--
-- Name: powerball_drawing_id_seq; Type: SEQUENCE; Schema: public; Owner: luckydna
--

ALTER TABLE public.powerball_drawing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.powerball_drawing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: luckydna
--

CREATE TABLE public.refresh_token (
                                      id bigint NOT NULL,
                                      expires_at timestamp(6) with time zone NOT NULL,
                                      token character varying(255) NOT NULL,
                                      user_id bigint NOT NULL
);


ALTER TABLE public.refresh_token OWNER TO luckydna;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: luckydna
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_play; Type: TABLE; Schema: public; Owner: luckydna
--

CREATE TABLE public.saved_play (
                                   id bigint NOT NULL,
                                   created_at timestamp(6) with time zone,
                                   play_date date,
                                   power_ball integer,
                                   white_ball1 integer,
                                   white_ball2 integer,
                                   white_ball3 integer,
                                   white_ball4 integer,
                                   white_ball5 integer,
                                   user_id bigint NOT NULL
);


ALTER TABLE public.saved_play OWNER TO luckydna;

--
-- Name: saved_play_id_seq; Type: SEQUENCE; Schema: public; Owner: luckydna
--

ALTER TABLE public.saved_play ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_play_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profile; Type: TABLE; Schema: public; Owner: luckydna
--

CREATE TABLE public.user_profile (
                                     id bigint NOT NULL,
                                     birthday date,
                                     favorite_numbers character varying(255),
                                     lucky_attributes character varying(255),
                                     user_id bigint NOT NULL
);


ALTER TABLE public.user_profile OWNER TO luckydna;

--
-- Name: user_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: luckydna
--

ALTER TABLE public.user_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: play_result play_result_pkey; Type: CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.play_result
    ADD CONSTRAINT play_result_pkey PRIMARY KEY (id);


--
-- Name: powerball_drawing powerball_drawing_pkey; Type: CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.powerball_drawing
    ADD CONSTRAINT powerball_drawing_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: saved_play saved_play_pkey; Type: CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.saved_play
    ADD CONSTRAINT saved_play_pkey PRIMARY KEY (id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: user_profile ukebc21hy5j7scdvcjt0jy6xxrv; Type: CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT ukebc21hy5j7scdvcjt0jy6xxrv UNIQUE (user_id);


--
-- Name: refresh_token ukr4k4edos30bx9neoq81mdvwph; Type: CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token);


--
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- Name: play_result fk4qdymhugq7le1qd9xnmyn0eqx; Type: FK CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.play_result
    ADD CONSTRAINT fk4qdymhugq7le1qd9xnmyn0eqx FOREIGN KEY (drawing_id) REFERENCES public.powerball_drawing(id);


--
-- Name: refresh_token fk5wkt2p042y3lwltk29cvpxuh; Type: FK CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fk5wkt2p042y3lwltk29cvpxuh FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: saved_play fk7qhs5wcl61mgwam7ykjsvt7sd; Type: FK CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.saved_play
    ADD CONSTRAINT fk7qhs5wcl61mgwam7ykjsvt7sd FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: play_result fkbjogy2lp3vufgbxxt6m2drjo9; Type: FK CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.play_result
    ADD CONSTRAINT fkbjogy2lp3vufgbxxt6m2drjo9 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: user_profile fkpdmw33px6fmevqhcy2lpstu4w; Type: FK CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT fkpdmw33px6fmevqhcy2lpstu4w FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: play_result fkrm0nr0g1gsb6yteumvcykiwnb; Type: FK CONSTRAINT; Schema: public; Owner: luckydna
--

ALTER TABLE ONLY public.play_result
    ADD CONSTRAINT fkrm0nr0g1gsb6yteumvcykiwnb FOREIGN KEY (saved_play_id) REFERENCES public.saved_play(id);


--
-- PostgreSQL database dump complete
--

\unrestrict PZc59U5p6ZkDKoiHLJsM2aRZ80eRQPFX7RFb7OaRsaLGNQl2AnqfbnEyghBpPpA

